### ISSUE TITLE
Doesn't open in Contao 4.3

### ISSUE THREAD

**Issue by bastibuck** [alnv/prosearch#2]
Hey Alexander,

just came across ProSearch for Contao and tried installing it in a up to date Contao 4.

Install works fine. DB is updated as expected and BE shows the new menu to build the search. Chose some tables, built the index and tried to fire the seach.
But it doesn't open on alt+m.

Tried assigning a custom shortcut but nothing worked. Also the backend doesn't show the link to open it via mouse.

Can you confirm it works in Contao 4.3? Do I need to activate the extension somewhere? What am I missing? 

Thanks,
Basti

**Comment by alnv** [comment]
All right. Solved this Problem in v1.0.12

**Comment by bastibuck** [comment]
Awesome thank you. Will check soon :-)
